# Generated by Django 4.2.8 on 2023-12-30 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set1', models.PositiveIntegerField()),
                ('set2', models.PositiveIntegerField()),
                ('set3', models.PositiveIntegerField(blank=True, null=True)),
                ('set4', models.PositiveIntegerField(blank=True, null=True)),
                ('set5', models.PositiveIntegerField(blank=True, null=True)),
                ('pontuacao', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Torneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo_torneio', models.CharField(max_length=50)),
                ('jogadores', models.ManyToManyField(through='eventos.Inscricao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inscricao',
            name='resultado_jogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.resultadojogo'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='torneio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.torneio'),
        ),
    ]
